### ISSUE TITLE
Can't remove liquidity for ETH-UDOO Pair

### ISSUE THREAD

**Issue by Ikabott-MRM** [Uniswap/uniswap-v2-periphery#40]
Transaction is successfully sent, but liquidity is not removed. 

Here I attach:
![remove liquidity sent](https://user-images.githubusercontent.com/68831287/88493785-69c1d000-cf89-11ea-9181-f51c98f2d8cb.png)

1 - Screenshot of confirmation (remove_liquidity_sent.png)
2 - Wallet Address (Argent wallet running on iOS): 0x652164D5FD53D1f7eaE245FF9545cC9F4888A400
3 - Transaction ID: 0x6b525d073b6f8bd1549f439617b23605ff8f27eb9834ed7e939d3e01ede86c12
4 - Token Address (Current): 0x12f649a9e821f90bb143089a6e56846945892ffb

Thanks in advance uniswap team!
Your app is AWESOME

**Comment by Ikabott-MRM** [comment]
I re tried, and got the same result. 
Here the new tx hash: 0xf9b1517cecafba6ddbd81ccf56f9d9bd85050c5b50afe65d436220338327162d

**Comment by Ikabott-MRM** [comment]
New attempt.
This one failed with error "Duplicate Request".  But I still the liquidity I want to remove
Txn Hash:0x47d432ee2744e5770b386dc2bc50863e0c8d728b5f3daf287030d4608abebdf1

**Comment by Ikabott-MRM** [comment]
Last update.
I don't know what happened.  RIGHT AFTER the failed transaction I pasted above, I got my tokens
https://etherscan.io/tx/0x66e05549d68a6841fd7551f037b85239323248d91d7c2dc6bedf360b008810ab

I don't understand.
Maybe my problem will help, if not, just close it. 
Thanks

**Comment by moodysalem** [comment]
Probably price movement, hard to tell because the argent relayer obscures the revert reason
