### ISSUE TITLE
UniswapV2Library pairFor() returns wrong address

### ISSUE THREAD

**Issue by MaxFeldman1** [Uniswap/uniswap-v2-periphery#42]
Hello, when working to integrate my project with Uniswap I ran into some trouble when interacting with the UniswapVRouter02 contract. Whenever I would attempt to add liquidity to a uniswap pair the transaction would always revert. 

I investigated further and detirmined that the cause of this was that the pairFor function in UniswapV2Library.sol was returning the wrong address value. It should be noted that this I had this error while using both a private ethereum network running on geth and while testing using ganache-cli. I must admit that I am not a master of the inner workings of the EVM. I do not claim to know the reasoning for the code on line 20 of UniswapV2Library.sol that assigns the return value. Though when I changed it to fetch the address from the uniswapV2factory itself this problem was solved. I believe that there is likely some reason that I don't understand as to why this is not a problem on the mainnet or the other public testnets because uniswap seems to not have this trouble on those networks.

Steps to reproduce:
```
git clone https://github.com/MaxFeldman1/reproduceError.git
cd reproduceError/uniswap-v2-periphery
npm i @uniswap/lib
npm i @uniswap/v2-core
truffle build
cd ../uniswap-v2-core
truffle build
#copy UniswapV2Router02 artifact to uniswap-v2-core
cp ../uniswap-v2-periphery/build/contracts/UniswapV2Router02.json ./build/contracts
#at this point you would like to spin up a local eth network such as ganache-cli
#be sure to add the tag --allowUnlimitedContractSize if you are using ganache-cli 
#or other tag suitable to your specific local eth instance as the UniswapV2Router bytesize will be over 24kb
#also make sure to NOT add the quiet tag to your eth instance

truffle test
#you can expect that the 'before each' test will pass before the 'adds liquidity' test fails
#find the hash of the most recent transaction in your local eth instance it should have reverted
#also make mental note of the address of the pair created you can find this in the events section underneath the failed test
#to debug the transaction we need to go back into the periphery contracts directory
cd ../uniswap-v2-periphery
truffle debug  #put transaction hash here
#place a break on UniswapV2Library.sol:26
b UniswapV2Library.sol:26
#I intentionally added line 26 to say 'return pair;' which has no effect other than  
#that while debugging you have the opportunity to find the returned value of the pairFor function before the transaction reverts
#to find the value enter the following
:pair
#if you compare this to the value shown in the pair created event there is a definite difference
#if you step through the few steps that are left in the transaction 
#it is apparent that this is the cause of the failure of the transaction
```
It should be noted that the only line I changed was line 21 of UniswapV2Library.sol and that was only for purposes of debugging the transaction. The transaction will still revert if this line is removed.

I should also alert you to the fact that this problem still occurs when instead of getting the artifact for UniswapV2Router02 locally I use the one linked to on github by Uniswap at unpkg.com though due to lack of original source code the latter artifact makes debugging cumbersome.

```
####$ truffle version
Truffle v5.1.24 (core: 5.1.24)
Solidity - 0.5.16 (solc-js) #when in uniswap-v2-core
Solidity - 0.6.6 (solc-js) #when in uniswap-v2-periphery
Node v12.16.2
Web3.js v1.2.1
```
I have used multiple eth instances so I do not believe this is the root of the problem though if you find it relevant the information is below
```
$ganache-cli --version
Ganache CLI v6.9.1 (ganache-core: 2.10.2)

$geth version
Geth
Version: 1.9.13-stable
Git Commit: cbc4ac264e9671898bff6ec7e434da3eca4bd273
Architecture: amd64
Protocol Versions: [65 64 63]
Go Version: go1.14.2
Operating System: linux
```

**Comment by moodysalem** [comment]
https://uniswap.org/docs/v2/smart-contract-integration/quick-start/#writing-tests
> Note you should only deploy the precompiled Uniswap contracts in the build directories for unit tests. This is because solidity appends a metadata hash to compiled contract artifacts which includes the hash of the contract source code path, and compilations on other machines will not result in the exact same bytecode. This is problematic because in Uniswap V2 we use the hash of the bytecode in the v2-periphery UniswapV2Library, to compute the pair address.
