### ISSUE TITLE
getting UniswapV2: LOCKED exception

### ISSUE THREAD

**Issue by alonmuroch** [Uniswap/uniswap-v2-periphery#44]
Hi Uniswap team, 
I've encountered an issue when trying to integrate with Uniswap, didn't find anything on google which is similar. 

I'm using Genache (forking mainnet).
IDE Remix
Deployment truffle

I did a simple contract which tries to exchange eth -> CDT (and erc20 token)

```
    function exchangeCDTUniswap(uint256 eth_amount) internal returns(uint256 cdt_bought) {
        address weth = IUniswapV2Router02(uniswap_router).WETH();

        address[] memory path = new address[](2);
        path[0] = weth;
        path[1] = cdt;

        uint[] memory amounts = IUniswapV2Router02(uniswap_router).swapExactETHForTokens{value:eth_amount}(1, path, address(this), now + 15);
        return amounts[1];
    }
```
uniswap_router = 0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D
cdt = 0x177d39ac676ed1c67a2b268ad7f1e58826e5b0af

From that call I get UniswapV2: LOCKED which, after looking around, only appears in UniswapV2Pair.sol ([here](UniswapV2Pair.sol))

What did I do wrong here?

**Comment by MicahZoltu** [comment]
That error indicates reentrance.  Is the token you are trying to swap calling into Uniswap on its transfer function?

**Comment by moodysalem** [comment]
This is a common issue with the ganache fork chain, for some reason the locked state is not correct. I would recommend deploying to your own test chain

**Comment by alonmuroch** [comment]
@MicahZoltu no, it's a plain old ERC20

@moodysalem have you encountered it before? seems a bit of an overkill deploying the whole uniswap project just for simple tests..

**Comment by moodysalem** [comment]
@alonmuroch only via the discord questions, I haven't encountered it myself, but you only have to deploy the uniswap factory and router. I would recommend a local testnet over a mainnet ganache fork for unit tests anyway. 

This is an issue with the ganache fork code, as the pool is always unlocked after a swap. Nothing we can do in the uniswap contracts to fix it.

**Comment by Samboy76** [comment]
I´m having the same issue in Hardhat deployment. https://github.com/Uniswap/v2-periphery/issues/159
