### ISSUE TITLE
using address[] memory path

### ISSUE THREAD

**Issue by glints** [Uniswap/uniswap-v2-periphery#46]
Hello,

I'm having some trouble with this:

```
address[] memory path = new address[](2);
path[0] = uniswapRouter.WETH();
path[1] = _tokenAddress;

```
path is typed as memory here, and when I try to pass it to swapETHForExactTokens it expects path to be of type calldata.
I receive this error: Type address[] memory is not implicitly convertible to expected type address[] calldata.

How can I convert this to the correct type? Thanks.

**Comment by moodysalem** [comment]
Please ask in the discord
