### ISSUE TITLE
failed to call addLiquidity on the rinkeby testnet using remix IDE

### ISSUE THREAD

**Issue by wenchaopeng** [Uniswap/uniswap-v2-periphery#47]
my operation is like this：

1. issued two ERC20 Tokens on rinkeby

   1. QLC: `0xc211a8cdfff90dca01280d7c90793845499f80a7`
   2. QETH: `0x8e212bdfb571ac7a4a149c4d631a03a63aa61ef5`

2. authorize these two tokens to the router contract,just call the approve method of the token contract,

   and I can check the authorization success through the allowance method

3. call the addLiquidity method of the router contract,router address on the rinkeby is `0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D`，my parameters are as follows

   1. tokenA:`0x8e212bdfb571ac7a4a149c4d631a03a63aa61ef5`         // QETH contract address
   2. tokenB:`0xc211a8cdfff90dca01280d7c90793845499f80a7`            // QLC contract address
   3. amountADesired:10000
   4. amountBDesired:10000
   5. amountAMin:0
   6. amountBMin:0
   7. to:`0xB2B98Ac2aC3EB419B17f6cdcA25A0241c3b31bcc`     //my wallet address
   8. deadline:1629107841

after doing this I encountered an error:

Gas estimation errored with the following message (see below). The transaction execution will likely fail. Do you want to force sending?
gas required exceeds allowance (10000000) or always failing transaction

Can you give me some advice on this error, many thanks

**Comment by moodysalem** [comment]
Please ask in the developer channel on discord, but you will need to force send or use eth_call to get the revert reason

**Comment by vinivst** [comment]
Did you figured this out? I'm facing the same error.

**Comment by Eteriaio** [comment]
Did you figured this out? I'm facing the same error.
