### ISSUE TITLE
About change the contract

### ISSUE THREAD

**Issue by flyhigh** [Uniswap/uniswap-v2-periphery#48]
I tried to change th uniswap-v2-core and uniswap-v2-periphery,changed the contract name and add some logics.
But when I deployed to chain and try to create a pair by init a pool, the uniswap-v2-interface call metamask faild, the error is :

inpage.js:1 MetaMask - RPC Error: gas required exceeds allowance (14937714) or always failing transaction {code: -32000, message: "gas required exceeds allowance (14937714) or always failing transaction"}
index.js:1 {code: -32000, message: "gas required exceeds allowance (14937714) or always failing transaction"}

Can anyone help me to slove it out?

**Comment by moodysalem** [comment]
This is not an issue with the uniswap periphery code. Please ask in the developers discord.
