### ISSUE TITLE
how to calculate the pairFor init code hash

### ISSUE THREAD

**Issue by fern-xian** [Uniswap/uniswap-v2-periphery#59]
how to calculate the pairFor init code hash? can you give a js example?

    function pairFor(address factory, address tokenA, address tokenB) internal pure returns (address pair) {
        (address token0, address token1) = sortTokens(tokenA, tokenB);
        pair = address(uint(keccak256(abi.encodePacked(
                hex'ff',
                factory,
                keccak256(abi.encodePacked(token0, token1)),
                hex'edf6876fa96311f9614f5d804cb3fd74f32d2ce90ea1b2ee31bae1b1a6118ac0' // init code hash
            ))));
    }

**Comment by moodysalem** [comment]
https://github.com/Uniswap/uniswap-sdk/blob/v2/src/entities/pair.ts#L30
