### ISSUE TITLE
I have a question in function getAmountIn

### ISSUE THREAD

**Issue by ByteRui** [Uniswap/uniswap-v2-periphery#64]
function getAmountIn(uint amountOut, uint reserveIn, uint reserveOut) internal pure returns (uint amountIn) {
        require(amountOut > 0, 'UniswapV2Library: INSUFFICIENT_OUTPUT_AMOUNT');
        require(reserveIn > 0 && reserveOut > 0, 'UniswapV2Library: INSUFFICIENT_LIQUIDITY');
        uint numerator = reserveIn.mul(amountOut).mul(1000);
        uint denominator = reserveOut.sub(amountOut).mul(997);
        amountIn = (numerator / denominator).add(1);
    }

Why is the last line needed call add(1)?

**Comment by ByteRui** [comment]
Oh, I know what it does。Just Compensates for lost decimals in calculation.

**Comment by a2468834** [comment]
Sorry, I didn't get it.

You mean: because `numerator / denominator` would be zero (with little possibility), we need to ensure the required input amount should always be positive (i.e., >0).

Is it right? Thanks for replying~

**Comment by Jeiwan** [comment]
@a2468834 Integer division in Solidity rounds towards zero, i.e. the result gets truncated. This leads to calculated input amount being too low to produce needed `amountOut`.
