### ISSUE TITLE
Why Does SwapToPrice Need The True Price When It Looks Up The Reserves On Chain

### ISSUE THREAD

**Issue by pointtoken** [Uniswap/uniswap-v2-periphery#67]
IN https://github.com/Uniswap/uniswap-v2-periphery/blob/master/contracts/examples/ExampleSwapToPrice.sol, there is a function for computeProfitMaximizingTrade, which takes the true price passed into the smart contract, as well as the reserves as calculated on chain in the smart contract. 

What oracle should one use for true price? I'm assuming NOT uniswap itself, because you could derive the price from uniswap onchain. Are you imagining using an Oracle like the sample smart contract oracle? https://github.com/Uniswap/uniswap-v2-periphery/blob/master/contracts/examples/ExampleOracleSimple.sol Or a price feed from somewhere other than Uniswap entirely?

**Comment by moodysalem** [comment]
'true price' is what you think the external price of the thing is, or what you wish to move the (marginal) price to.
for example, if uniswap's price is 10 dai per eth, and you think the price is actually 8 dai per eth, then you would pass 8 and 1

please join the developer channel on discord if you have more questions

**Comment by liximomo** [comment]
`truePriceTokenB` should always be 1, am i right?

**Comment by moodysalem** [comment]
not necessarily, solidity does not have decimals so you are passing in a ratio, e.g. truePriceTokenA = 2, truePriceTokenB = 3 would represent a price of ~0.66666666 tokenA / tokenB
