### ISSUE TITLE
non-deterministic test

### ISSUE THREAD

**Issue by NoahZinsmeister** [Uniswap/uniswap-v2-periphery#7]
investigate why [L143 of ExampleFlashSwap](https://github.com/Uniswap/uniswap-v2-periphery/blob/master/test/ExampleFlashSwap.spec.ts#L143) intermittently fails

**Comment by moodysalem** [comment]
This most likely has to do with the gas being paid for the transaction being inconsistent

Why that's happening I'm not sure
