### ISSUE TITLE
Problem using UniswapRouter swapTokensForExactTokens on Kovan Network

### ISSUE THREAD

**Issue by RadNi** [Uniswap/uniswap-v2-periphery#83]
I'm trying to make a wrapper contract to exchange token for exact tokens. But all the time I get the error: 
`Gas estimation errored with the following message (see below). The transaction execution will likely fail. Do you want to force sending?
The execution failed due to an exception. Reverted`

(I'm sure that I set a proper gas limit)

Here is the contract code:

    pragma solidity =0.6.6;

    import "https://github.com/Uniswap/uniswap-v2-periphery/blob/master/contracts/interfaces/IUniswapV2Router02.sol";
    
    contract UniswapExample {
        address internal constant UNISWAP_ROUTER_ADDRESS = 0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D ;
        IUniswapV2Router02 public uniswapRouter;
        
        constructor() public {
            uniswapRouter = IUniswapV2Router02(UNISWAP_ROUTER_ADDRESS);
        }

        function convertTokenToToken() public {    
            address[] memory path = new address[](2);
            path[0] = 0xd0A1E359811322d97991E03f863a0C30C2cF029C;
            path[1] = 0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984;
            uint amountOut = 1000000000000000000;
            uint amountInMax = 81421557334496861;
            address to = 0x9924b75Af301D9F2801DEA27f598fc8156c71732;
            uint deadline = 1669238436;
            // Exchanging WETH for 1 UNI
            uniswapRouter.swapTokensForExactTokens(amountOut, amountInMax, path, to, deadline);

          }
    }

The amountInMax at the time of writing was sufficient for the swap.
Deployed contract address at Kovan network: [0x22eea44c390F23fA7F1420C233e20d1e061f4B48](https://kovan.etherscan.io/address/0x22eea44c390f23fa7f1420c233e20d1e061f4b48)

**Comment by moodysalem** [comment]
Not sure, but you can send the transaction anyway to get the revert reason, and this question is more appropriate for the Discord

**Comment by aress31** [comment]
@moodysalem I must disagree sadly Discord is not useful at all, Uniswap should invest in better dev support!

**Comment by RadNi** [comment]
Just in case, guys in the discord channel helped me a lot. I forgot to do three things before calling `swapTokensForExactTokens` .
1. Calling `allow` function for the input token from the user wallet in order to activate `transferFrom` function from the `UniswapExample` contract.
2. Calling 'allow' function for the input token from the `UniswapExample` to allow the Uniswap router contract for spending `UniswapExample's` funds.
3. Transferring user's fund to the `UniswapExample` contract using the `transfer` function of the input contract.

This is because the `message.sender` object refers to the calling agent (Either external call from an intermediary contract, or directly from the user). Therefore, since in my case I am calling the Uniswap's contract from an intermediary contract, the `message.sender` object is `UniswapExample` contract, and in order to perform a swap, we have to prepare everything for the intermediary contract, like allowing Uniswap's contracts and transferring funds to it.
