### ISSUE TITLE
swapExactETHForTokens() on nodejs its getting reverted by EVM 

### ISSUE THREAD

**Issue by 6eer** [Uniswap/uniswap-v2-periphery#90]
Hi, im working on a truffle mainnet fork and im trying to execute a swapExactETHForTokens() using web3 but for some reason that i cant understand the swap its getting reverted. Sadly the error message say nothing but revert. Can anyone bring me some help or some insigths, im really stuck.

The code

`module.exports = async function(callback) {

    try {
        const accounts = await web3.eth.getAccounts()
        const sender = accounts[0]
        const receiver = accounts[1]

        const UniswapV2Router02 = require('./build/contracts/IUniswapV2Router02.json')
        const daiAddress = '0x6b175474e89094c44da98b954eedeac495271d0f'
        const ethAddress = '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2' 
        const uniRouter02 = new web3.eth.Contract(
           UniswapV2Router02.abi,'0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D')

        const amount = await uniRouter02.methods.swapExactETHForTokens(
            0,
            [ethAddress,daiAddress],
            //[daiAddress,ethAddress],
            receiver,
            1650370580)
            .send({from:sender,value:web3.utils.toWei('5000','Ether')})        

    }
    catch(error) {
    console.log(error)
    }

    callback()
}`

I appreciate any kind of help

**Comment by moodysalem** [comment]
Not sure what's going wrong--please ask in the developer channel of Discord
